const List<Map<String, dynamic>> langs = [
  {
    'popular-products': 'Популярные товары',
    'new-products': 'Новые товары',
    'add-product': 'Добавить',
    'search-text': 'Поиск',
    'price': 'Цена',
    'category': 'Категория',
    'type': 'Типоразмер',
    'producer': 'Производитель',
    'have': 'В наличии',
    'have-status-many': 'Много',
    'have-status-none': 'Нету',
    'order-with-number': 'Заказ номер ',
    'orders-none': 'Заказов нет',
    'detail': 'Подробнее',
    'empty_cart': 'Корзина пуста',
    'order-count': 'Количество: ',
    'order-count_addition': 'Количество доп заказа: ',
    'total': 'Итог',
    'set_order': 'Заказать',
    'products_in_cart': 'Товары в корзине',
    'currency': ' \$',
    'warehouse_missed': 'На складе не достаточно товаров: ',
    'workload_products': 'Минимальное кол-во товаров ',
    'popular_products': 'Ходовые товары необходимо изменить количество: ',
    'limit_message':
        'Вы не можете заказать из-за увелечения вашего долга, чтобы заказать, пожалуйста погасите долг',
    'main_bar': 'Главная',
    'orders_bar': 'Заказы',
    'cart_bar': 'Корзина',
    'profile_bar': 'Профиль',
    'myOrders': 'Мои Заказы',
    'akt_sverki': 'Акт сверки',
    'settings': 'Настройки',
    'logout': 'Выйти',
    'akt_sverki_detail': 'Акт сверки (детализированные)',
    'account_bonus': 'Отчет по бонусу',
    'deficit_list': 'Дефицитный лист',
    'changeLangText': 'Сменить язык',
    'login': 'Логин',
    'password': 'Пароль',
    'enter': 'Войти',
    'username': 'Имя пользователя',
    'check_user': 'Нету пользователя? ',
    'reg': 'Зарегистрируйтесь',
    'filter': 'Фильтр',
    'filter_action': 'Фильтровать',
    'balance': 'Баланс',
    'subdivision': 'Подразделение',
    'review': 'Отзыв',
    'exchange': 'Курс валюты',
    'delete_all': 'Удалить данные'
  },
  {
    'popular-products': 'Popular products',
    'new-products': 'New products',
    'add-product': 'Add',
    'search-text': 'Search',
    'price': 'Price',
    'category': 'Category',
    'type': 'TypeSize',
    'producer': 'Producer',
    'have': 'In stock',
    'have-status-many': 'Many',
    'have-status-none': 'None',
    'order-with-number': 'Order number ',
    'detail': 'Detail',
    'order-count': 'Count: ',
    'order-count_addition': 'Count addition: ',
    'orders-none': 'Orders none',
    'empty_cart': 'Cart is empty',
    'total': 'Total',
    'set_order': 'Make an order',
    'products_in_cart': 'Products in cart',
    'currency': ' \$',
    'warehouse_missed': 'There are not enough goods in stock: ',
    'workload_products': 'Minimum number of products: ',
    'popular_products': 'Running goods need to change the quantity: ',
    'limit_message':
        'You can`t order because of the increase in your debt, to order, please pay off the debt',
    'main_bar': 'Main',
    'orders_bar': 'Orders',
    'cart_bar': 'Cart',
    'profile_bar': 'Profile',
    'myOrders': 'My Orders',
    'akt_sverki': 'Act Compare',
    'settings': 'Settings',
    'logout': 'Logout',
    'akt_sverki_detail': 'Act Compare(detail)',
    'account_bonus': 'Bonus report',
    'deficit_list': 'Deficit list',
    'changeLangText': 'Change Language',
    'login': 'Login',
    'password': 'Password',
    'enter': 'Enter',
    'username': 'Username',
    'check_user': 'No user? ',
    'reg': 'Create account',
    'filter': 'Filter',
    'filter_action': 'Filter',
    'balance': 'Balance',
    'subdivision': 'Subdivision',
    'review': 'Review',
    'exchange': 'Rate exchange',
    'delete_all': 'Delete data'
  },
  {
    'popular-products': 'Оmmabop mahsulotlar',
    'new-products': 'Yangi mahsulotlar',
    'add-product': 'Qo`shing',
    'search-text': 'Topish',
    'price': 'Narx',
    'category': 'Turkum',
    'type': 'Hajmi',
    'producer': 'Ishlab chiqaruvchi',
    'have': 'Mavjud',
    'have-status-many': 'Ko`p',
    'have-status-none': 'Yo`q',
    'order-with-number': 'Buyurtma № ',
    'orders-none': 'Buyurtma yo`q',
    'detail': 'Batafsil',
    'order-count': 'Son: ',
    'order-count_addition': 'Qo`shimcha Son: ',
    'empty_cart': 'Arava bo`sh',
    'total': 'Jami',
    'set_order': 'Buyurtma',
    'products_in_cart': 'Savatdagi mahsulotlar',
    'currency': ' \$',
    'warehouse_missed': 'Zaxirada tovarlar etarli emas: ',
    'workload_products': 'Mahsulotlarning minimal soni: ',
    'popular_products': 'Ishlaydigan tovarlar miqdorini o`zgartirish kerak: ',
    'limit_message':
        'Siz buyurtma berish uchun qarzingizni oshirganingiz uchun buyurtma berolmaysiz, iltimos qarzni to`lang',
    'main_bar': 'Asosiy',
    'orders_bar': 'Buyurtma',
    'cart_bar': 'Savat',
    'profile_bar': 'Profil',
    'myOrders': 'Buyurtmalar',
    'akt_sverki': 'Act sverka',
    'settings': 'Sozmalar',
    'logout': 'Chiqish',
    'akt_sverki_detail': 'Act sverka(batafsil)',
    'account_bonus': 'Bonus Hisoboti',
    'deficit_list': 'Noyob Varaq',
    'changeLangText': 'Tilni o`zgartirish',
    'login': 'Login',
    'password': 'Parol',
    'enter': 'Kirish',
    'username': 'Foydalanuvchi',
    'check_user': 'Foydalanuvchi yo`qmi? ',
    'reg': 'Yaratish',
    'succes_auth': '',
    'connection_error': '',
    'filter': 'Filtr',
    'filter_action': 'Filtrlash uchun',
    'balance': 'Balans',
    'subdivision': 'Bulinma',
    'review': 'Fikr bildirish',
    'exchange': 'AKSH valuta kursi',
    'delete_all': 'Ma`lumotlarni o`chirish'
  },
];
